# Generated by Django 4.2.7 on 2023-12-21 14:59

from django.db import migrations, models
import domain.user.models.Document


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_upload',
            field=models.FileField(upload_to=domain.user.models.Document.user_directory_path),
        ),
    ]
