# Generated by Django 4.2.7 on 2023-12-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_user', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprofile',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='middle_name',
        ),
    ]
