# Generated by Django 4.2.7 on 2023-12-03 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_department_employmenttype_joblevel_worksetup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_profile_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('is_rest_day', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkInformation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_information', to='system.department')),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_information', to='system.employmenttype')),
                ('job_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_information', to='system.joblevel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_information', to=settings.AUTH_USER_MODEL)),
                ('work_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_information', to='system.worksetup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
