# Generated by Django 4.2.7 on 2023-12-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_historicalworkschedule_historicalworkinformation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='file_upload',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
