# Generated by Django 4.2.7 on 2023-12-30 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_fromemail_historicalfromemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='from_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='mailer.fromemail'),
        ),
    ]
